### ISSUE TITLE
建议资产图片可以直接大图预览

### ISSUE THREAD

**Issue by linhaikun2019** [celaraze/cela#115]
### 须知

1，更希望用户能提供 PR 来增加新工能，而不是在 Issue 中表述。
2，建议的新功能，也不一定开发和实装。

### 你的想法

请说。
现在的资产清单要想查看大图还需要进入详情才能查看，希望可以直接做成类似那种大图播放的模式，参考elementUI的模式
![搜狗截图20231214200808](https://github.com/celaraze/cat/assets/50667512/02cbafd4-0880-43ee-816f-50577b9257d8)
![搜狗截图20231214200821](https://github.com/celaraze/cat/assets/50667512/fa0ea9b9-65ad-42cf-820f-83907772d38e)
![搜狗截图20231214200940](https://github.com/celaraze/cat/assets/50667512/7ea021b3-ec52-4ff0-a0f6-1ca6c3bc8d64)

**Comment by linhaikun2019** [comment]
另外，日志功能只有一个导入日志的问题上次说过了，希望下个版本完善

**Comment by linhaikun2019** [comment]
还可以尝试加一个资产打印的功能，现在都是导出excel表，建议可以直接使用诸如printJS进行网页打印

**Comment by celaraze** [comment]
1，大图有空重写下表格的图片字段，暂时不会考虑优先处理。资产数据应被结构化存储并检索，图片只是佐证和留痕，多点击一下进详情页看大图无妨。

2，日志我说过了，这个是想到一个加一个，目前导入日志迫切需要否则用户不知道导入作业的详细结果，因此才特地加了一个日志模块，实际上，日志构建再 `logs` 中都有记录，自行调整 `.env` 中的 `log_level` 可实现。这属于运维范畴的参考，没必要做成非常详细的前台模块展示。

3，参考文档中的常见问题。

另外，请不要单个 Issue 提交多个问题。
