### ISSUE TITLE
新增用户的窗口中，希望加一个“组织选择”入口

### ISSUE THREAD

**Issue by YC119** [celaraze/cela#126]
### 须知

1，更希望用户能提供 PR 来增加新工能，而不是在 Issue 中表述。
2，建议的新功能，也不一定开发和实装。

### 你的想法

新增用户的窗口中，观察到近期已迭代出“角色选择”的入口，希望再加一个“组织选择”的入口进去

**Comment by celaraze** [comment]
组织暂无其它使用需求，仅初期框架搭完后先写好，后续相关功能实装后再考虑。
