### ISSUE TITLE
增加一个门店组织吧

### ISSUE THREAD

**Issue by xiaoxiaoyaonie** [celaraze/cela#133]
如题   增加添加门店功能   如果可以 你可以出个windows 程序 windows 运行 提取 info 配置信息 读取服务器地址 ,
加入一个门店选项 加入填写使用人    确定上传配置信息到服务器

**Comment by celaraze** [comment]
这是标准的、泛用的 IT 运维平台，不会针对某个场景做客制化的开发。如果有门店使用场景，可以使用组织实现。一个门店相当于组织下的一个部门即可。

配置脚本暂无开发计划，如果决定要做就不能单独为 Windows 平台考虑，多平台的客户端程序会徒增开发成本，目前仅有我一人在开发，如果乐意的话，这部分可以协助开发并提交 PR 合并。
