### ISSUE TITLE
麻烦作者尽快更新位置字段

### ISSUE THREAD

**Issue by linhaikun2019** [celaraze/cela#136]
### 须知

1，更希望用户能提供 PR 来增加新工能，而不是在 Issue 中表述。
2，建议的新功能，也不一定开发和实装。

### 你的想法

作者大大，现在这个资产系统已整体形成雏形，但可惜就是缺一个位置字段，资产总是有位置的啊，要不然在仓库，要不然在哪个楼等等，连位置都没有就不能称之为一个完整的资产管理系统，不知作者为什么不考虑在第一版就加入位置，现在更新了这么多版一直缺失很不解

**Comment by celaraze** [comment]
位置字段会在区域管理中体现，当前版本无该功能。这不是一个字段的事情，你的理解太过浅表，如果单纯为了记录位置，暂时可以使用额外信息字段。这是我的开源项目，并不是全职维护，有时间我会做的，但请不要把它当成理所当然。
