### ISSUE TITLE
导入窗口小分辨率显示器显示不完全也不能滚动

### ISSUE THREAD

**Issue by linhaikun2019** [celaraze/cela#145]
### 先确认

***1，是否使用最新版本。***
答：是

***2，是否有跳过应用处理逻辑，而自行修改数据库结构、数据等操作。***
答：否

***3，是否有二次开发操作。***
答：否

### 再描述

***1，你的 PHP 、 MySQL 版本号。***
答：php:8.3 mysql:8.0

***2，当前使用的 CAT 版本号。***
答：1.0.5

***3，你遇到了什么问题，尽量描述清楚，尤其是附上错误内容。***
答：如图所示，导入设备资产列表因为输入框很多造成小分辨率显示器下显示不完全且不能滚动
![搜狗截图20240217093547](https://github.com/celaraze/cat/assets/50667512/1de4b4f9-1d5f-4be3-9785-b46c74fccbbc)

**Comment by celaraze** [comment]
额，这对低分辨率机器放弃适配的，尽可能用 720p 以上。实在不行，用浏览器的缩放缩小点吧。

**Comment by linhaikun2019** [comment]
我这是1920*1080的分辨率还是不行啊，实在不行只能缩放了

**Comment by celaraze** [comment]
你这界面看着不像 1080p 啊，截图截全了吗，我在 720 都能正常显示的。

**Comment by linhaikun2019** [comment]
没截全，我只截了一部分，我分辨率是1920*1080的，这个后期能修复一下吗？

**Comment by celaraze** [comment]
我后面模拟下小屏幕看看
