### ISSUE TITLE
冒昧问一下，新版大概啥时候更新啊？

### ISSUE THREAD

**Issue by linhaikun2019** [celaraze/cela#149]
### 须知

1，更希望用户能提供 PR 来增加新工能，而不是在 Issue 中表述。
2，建议的新功能，也不一定开发和实装。

### 你的想法

目前1.0.5版本已经过去几个月了，不知今年有望新版本的推出计划吗，预计更新的内容和时间范围能否告知一下，此问题本不算issue,只是个疑问，谢谢！

**Comment by celaraze** [comment]
这两月比较忙，有时间了会更新的。
