### ISSUE TITLE
新建组织后再查看或编辑报错

### ISSUE THREAD

**Issue by RealfuRyZ** [celaraze/cela#150]
### 先确认

***1，是否使用最新版本。***
答：是

***2，是否有跳过应用处理逻辑，而自行修改数据库结构、数据等操作。***
答：使用独立MySQL数据库

***3，是否有二次开发操作。***
答：无

### 再描述

***1，你的 PHP 、 MySQL 版本号。***
答：PHP8.1.27，MySQL8.1

***2，当前使用的 CAT 版本号。***
答：git最新版本呢

***3，你遇到了什么问题，尽量描述清楚，尤其是附上错误内容。***
答：通过宝塔方式安装后，新建组织，再点击cat或者编辑出现500错误，已打开debug模式生成了错误信息https://flareapp.io/share/67OWwwA7#stack
![image](https://github.com/celaraze/cat/assets/64892747/822d8569-abe4-4ad8-b217-ad85693903aa)

**Comment by celaraze** [comment]
组织功能还没正式完成，关注后续更新。

**Comment by RealfuRyZ** [comment]
> 组织功能还没正式完成，关注后续更新。
好的 感谢回复
