### ISSUE TITLE
怎么创建账号

### ISSUE THREAD

**Issue by liuxingwai** [celaraze/cela#153]
docker部署完成后，怎么创建用户和密码，数据库也更新创建了，就是没有账号密码![mmexport1710530858454.png](https://github.com/celaraze/cat/assets/61938995/10baf382-cdcf-45e8-abd7-cb3a35d3acfb)

**Comment by liuxingwai** [comment]
更新数据库后，user表中没有任何数据，在数据库中加入了用户名和密码，登陆后无法识别

**Comment by celaraze** [comment]
1，chemex 已经停止维护，有相关问题请求助社区。
2，这里是 cat，请不要发布无关issue。

**Comment by liuxingwai** [comment]
我创建数据库是将数据库名称改成chemex了，实际我用的就是cat

**Comment by celaraze** [comment]
安装步骤不正确、缺少数据库迁移步骤。

`php artisan migrate`

`php artisan db:seed`
