### ISSUE TITLE
发现几个小问题

### ISSUE THREAD

**Issue by finer04** [celaraze/cela#155]
### 先确认

***1，是否使用最新版本。***
答：是（使用 docker-hub 的最新 latest）

***2，是否有跳过应用处理逻辑，而自行修改数据库结构、数据等操作。***
答：无

***3，是否有二次开发操作。***
答：无

### 再描述

***1，你的 PHP 、 MySQL 版本号。***
答：就是容器环境

***2，当前使用的 CAT 版本号。***
答：1.0.10-beta

***3，你遇到了什么问题，尽量描述清楚，尤其是附上错误内容。***
答：新账号改密码后登出报错 / 批量导入 CSV 后再在 web 界面添加资产出错 / 在 WPS 编辑的 CSV 模板要手动转换 UTF-8

1. 在个人资料更换密码后，再点击其他链接后报错（Route [login] not defined.），直接登出也报错。回到首页的登录界面才正常。我觉得更改密码后应系统要跳转注销比较合理一点。
![image](https://github.com/celaraze/cat/assets/24224180/c70d904c-f2de-43b1-b8f2-22a3c258f0a4)

2. 如果我用 CSV 模板批量导入资产的话，且我的资产编号顺延着系统原来的编号，在导出成功后，我在 Web 界面再人工添加资产的时候会报错。截图我没存下来。大概意思是编号重复了。

例如原来在 CAT 系统的资产编号是
DEVICE-0001
DEVICE-0002

然后我在 CSV 模板导入的资产编号顺延着系统的资产编号
DEVICE-0003
DEVICE-0004

然后接下来我再手动在 Web 添加资产，系统却自动生成了 DEVICE-0003 这个编号，与我手动导入的资产编号重复了无法添加。我只能改规则或者等到下一天才能纳入资产。我觉得要不 CSV 模板导入资产的时候，系统可以根据用户选择，自动生成资产编号或按照 csv 文件的资产编号导入。

3. 如果我在 WPS 编辑的 CSV，导入到系统的话，需要转换 UTF-8 格式才能导入进去。我可能要去 sublime 重新保存成 UTF8 编码才行。

![image](https://github.com/celaraze/cat/assets/24224180/d3a3c158-d436-48e4-972c-77a51ee628d8)

以上是我发现的一些小问题。总体体验下来作者的 cat 系统挺不错的够一个小团队用。

如果不介意的话我还有几个想法，如果可以实现的话更好。
1. 在资产管理能显示额外信息。（有时候想筛选 IP 地址或机柜位置，在资产界面搜索 IP 却查不了，只能在设备名称上加 IP 可以搜索到）
2. 工单系统的创建新工单的话，资产编号可以不是必须的嘛？（因为会考虑到新设备还没上架，我想在工单系统先创建上架工单，施工完毕后再创建新资产后在工单关联到新资产）。

**Comment by celaraze** [comment]
1 和 2 问题确实存在，后续我修复下，近期公司业务繁忙，暂时没有时间做维护，延后些。

本来是有 IP 地址管理功能的计划，这部分也是放在后面去处理了。
工单部分我会考虑做成可选。

**Comment by finer04** [comment]
> 1 和 2 问题确实存在，后续我修复下，近期公司业务繁忙，暂时没有时间做维护，延后些。
> 
> 本来是有 IP 地址管理功能的计划，这部分也是放在后面去处理了。 工单部分我会考虑做成可选。

好的，期待新版本，我这边也将就先用着~
